### PR TITLE
Use SLF4J, avoid interfering with application logging

### PR DESCRIPTION
**Pull request by ebaron**
When testing with EAP, we found a conflict with our JUL logging and EAP's logging that prevented it from starting. This PR ports over the logging setup from https://github.com/cryostatio/cryostat-agent that avoids this problem using an SLF4J configuration that avoids conflicts with the host application's logging.

This implementation was originally done by @andrewazores

### CODE REVIEW

**Review by andrewazores — COMMENTED** [review]
Looks like it matches the cryostat-agent workaround.

**Comment by ebaron** [comment]
We're seeing similar errors with EAP in Cryostat on OpenShift, converting this to a draft until we've figured it out.

**Comment by ehsavoie** [comment]
You should use MODULE_OPTS instead of JAVA_OPTS to pass your agent thus you would avoid that issue

**Comment by ebaron** [comment]
> We're seeing similar errors with EAP in Cryostat on OpenShift, converting this to a draft until we've figured it out.

This turned out to be due to a separate issue where the same crash occurs by enabling remote JMX (with or without an agent): https://access.redhat.com/solutions/312453

> You should use MODULE_OPTS instead of JAVA_OPTS to pass your agent thus you would avoid that logmanager issue

I tried this and it works well for EAP 7.4.0+, but this could still help to simplify installing our agent with older versions of EAP.

**Review by kittylyst — APPROVED** [review]
LGTM.

**Pull request merged**
